apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-tracer-client-deploy

spec:
  selector:
    matchLabels:
      name: v-tracer-client-app

  template:
    metadata:
      labels:
        name: v-tracer-client-app

    spec:
      containers:
        - name: v-tracer-client
          image: sjc.vultrcr.com/xanny/client
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5" # CPU 제한을 0.5 코어로 설정
              memory: "256Mi" # 메모리 제한을 512MB로 설정
            requests:
              cpu: "0.2" # CPU 요청을 0.2 코어로 설정
              memory: "128Mi"
