apiVersion: v1
kind: Service
metadata:
  name: v-tracer-client-service

spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    name: v-tracer-client-app