---
global:
  domain: argo.xanny.us

configs:
  cm:
    admin.enabled: false
  params:
    server.disable.auth: true
    # server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      #cert-manager.io/cluster-issuer: letsencrypt-prod
      #kubernetes.io/tls-acme: "true"    
      #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #tls: true

