loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /tmp/loki
    replication_factor: 1
  storage:
    bucketNames:
      chunks: 
      ruler: 
      admin: 
    type: s3
    s3:
      endpoint: 
      region: 
      secretAccessKey: 
      accessKeyId: 
      s3ForcePathStyle: true
    filesystem: null
  schemaConfig:
    configs:
      - from: "2023-01-05"
        store: tsdb
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h
  compactor:
    compaction_interval: 10m
    shared_store: s3
    retention_enabled: true
    retention_delete_delay: 2h

singleBinary:
  replicas: 1
  persistence:
   enableStatefulSetAutoDeletePVC: false
   enabled: false


