---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v-tracer-client-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:KOCEAN33/xanny-cluster.git
    targetRevision: main
    path: apps/v-tracer/environments/production/client
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true